### ISSUE TITLE
Importing FreeCAD in 3.7 segfaults in macOS 10.15

### ISSUE THREAD

**Issue by johnkgamble** [conda-forge/freecad-feedstock#28]
Issue: When installing conda from a fresh Miniconda environment using python 3.7 in macOS 10.15, python segfaults on FreeCAD import. Repro steps:

```
$ conda create -n fcenv python=3.7
$ conda activate fcenv
$ conda install freecad
$ python
>>> import os, sys
>>> sys.path.append(os.path.join(os.environ["CONDA_PREFIX"], "lib"))
>>> import FreeCAD
[1]    12659 segmentation fault  python
```

Note that the defaults pull FreeCAD 0.18.3, but I haven't had luck with 0.18.2 or 0.18.1.

<br/>
Environment (<code>conda list</code>):
<details>

```
$ conda list
# packages in environment at /Users/username/opt/miniconda3/envs/fcenv:
#
# Name                    Version                   Build  Channel
boost-cpp                 1.70.0               h75728bb_2    conda-forge
bzip2                     1.0.8                h01d97ff_1    conda-forge
ca-certificates           2019.9.11            hecc5488_0    conda-forge
certifi                   2019.9.11                py37_0    conda-forge
coin3d                    4.0.0             h26c4a4f_1006    conda-forge
curl                      7.65.3               h22ea746_0    conda-forge
expat                     2.2.5             h4a8c4bd_1004    conda-forge
freecad                   0.18.3           py37h4764a83_2    conda-forge
freetype                  2.10.0               h24853df_1    conda-forge
future                    0.18.1                   py37_0    conda-forge
hdf4                      4.2.13            hf3c6af0_1002    conda-forge
hdf5                      1.10.5          nompi_h3e39495_1104    conda-forge
icu                       64.2                 h6de7cb9_1    conda-forge
jpeg                      9c                h1de35cc_1001    conda-forge
jsoncpp                   1.8.4             ha1b3eb9_1001    conda-forge
krb5                      1.16.3            hcfa6398_1001    conda-forge
libblas                   3.8.0               14_openblas    conda-forge
libcblas                  3.8.0               14_openblas    conda-forge
libclang                  8.0.1                h770b8ee_1    conda-forge
libcurl                   7.65.3               h16faf7d_0    conda-forge
libcxx                    9.0.0                h89e68fa_1    conda-forge
libedit                   3.1.20170329      hcfe32e1_1001    conda-forge
libffi                    3.2.1             h6de7cb9_1006    conda-forge
libgfortran               4.0.0                         2    conda-forge
libiconv                  1.15              h01d97ff_1005    conda-forge
liblapack                 3.8.0               14_openblas    conda-forge
libllvm8                  8.0.1                h770b8ee_0    conda-forge
libnetcdf                 4.6.2             h1a02027_1003    conda-forge
libopenblas               0.3.7                h4bb4525_2    conda-forge
libpng                    1.6.37               h2573ce8_0    conda-forge
libssh2                   1.8.2                hcdc9a53_2    conda-forge
libtiff                   4.0.10            h3527a1b_1004    conda-forge
libxml2                   2.9.9                h12c6b28_5    conda-forge
libxslt                   1.1.33               h320ff13_0    conda-forge
llvm-openmp               9.0.0                h40edb58_0    conda-forge
lz4-c                     1.8.3             h6de7cb9_1001    conda-forge
ncurses                   6.1               h0a44026_1002    conda-forge
netgen                    6.2.1808        py37hd7f4ea3_1006    conda-forge
nspr                      4.20              h0a44026_1000    conda-forge
nss                       3.47                 hcec2283_0    conda-forge
numpy                     1.17.3           py37hde6bac1_0    conda-forge
occt                      7.3.0             hc05df86_1005    conda-forge
openssl                   1.1.1c               h01d97ff_0    conda-forge
pip                       19.3.1                   py37_0    conda-forge
pivy                      0.6.5a3          py37h02c1c16_0    conda-forge
pthread-stubs             0.4               h1de35cc_1001    conda-forge
pyside2                   5.13.1           py37h2815f34_4    conda-forge
python                    3.7.3                h93065d6_1    conda-forge
pyyaml                    5.1.2            py37h01d97ff_0    conda-forge
qt                        5.12.5               h1b46049_0    conda-forge
readline                  8.0                  hcfe32e1_0    conda-forge
setuptools                41.4.0                   py37_0    conda-forge
six                       1.12.0                py37_1000    conda-forge
smesh                     8.3.0.2              hbe4f68f_6    conda-forge
soqt                      1.6.0a            h93cf301_1003    conda-forge
sqlite                    3.30.1               h93121df_0    conda-forge
tbb                       2019.9               ha1b3eb9_0    conda-forge
tk                        8.6.9             h2573ce8_1003    conda-forge
vtk                       8.2.0           py37hcba847f_203    conda-forge
wheel                     0.33.6                   py37_0    conda-forge
xerces-c                  3.2.2             hbda6038_1004    conda-forge
xz                        5.2.4             h1de35cc_1001    conda-forge
yaml                      0.1.7             h1de35cc_1001    conda-forge
zlib                      1.2.11            h0b31af3_1006    conda-forge
zstd                      1.4.3                he7fca8b_0    conda-forge
```
</details>

<br/>
Details about  <code>conda</code> and system ( <code>conda info</code> ):
<details>

```
$ conda info
     active environment : fcenv
    active env location : /Users/username/opt/miniconda3/envs/fcenv
            shell level : 2
       user config file : /Users/username/.condarc
 populated config files : /Users/username/.condarc
          conda version : 4.7.12
    conda-build version : not installed
         python version : 3.7.4.final.0
       virtual packages : 
       base environment : /Users/username/opt/miniconda3  (writable)
           channel URLs : https://conda.anaconda.org/conda-forge/osx-64
                          https://conda.anaconda.org/conda-forge/noarch
                          https://repo.anaconda.com/pkgs/main/osx-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/osx-64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : /Users/username/opt/miniconda3/pkgs
                          /Users/username/.conda/pkgs
       envs directories : /Users/username/opt/miniconda3/envs
                          /Users/username/.conda/envs
               platform : osx-64
             user-agent : conda/4.7.12 requests/2.22.0 CPython/3.7.4 Darwin/19.0.0 OSX/10.15
                UID:GID : 501:20
             netrc file : None
           offline mode : False
```
</details>

**Comment by looooo** [comment]
> Note that the defaults pull FreeCAD 0.18.3, but I haven't had luck with 0.18.2 or 0.18.1.

Can you try using one of the dev builds:
`conda install freecad -c freecad/label/dev`

**Comment by johnkgamble** [comment]
@looooo , that worked. Thanks! Feel free to close or leave open as a hint to others with the same issue.

**Comment by looooo** [comment]
@johnkgamble Thanks for reporting. With the upcoming 0.18.4 this should be fixed also for the conda-forge packages.

**Comment by likewei92** [comment]
@looooo FYI I'm on 0.18.4 from conda-forge and I'm still getting the seg fault. Installing from `freecad/label/dev` worked for me as well

**Comment by looooo** [comment]
@likewei92 Thanks for reporting. It's possible we added some commits targeting this issue, but I can't remember exactly. Anyway, I don't think it's due to recipe differences. So let's focus on the 0.19 release for now.
